plugins:
  - jekyll-feed
author:
  first_name: Mária
  surname: Žuffová
  title: Reasearcher
  location: Fiesole, Italy
  image: /assets/img/zuffova_profile.png
social:
  linkedin: https://www.linkedin.com/in/maria-zuffova-75a48610/
  twitter: https://twitter.com/mariazuffova
  researchgate: https://www.researchgate.net/profile/Maria_Zuffova2
  facebook: " "
url: https://mariazuffova.com
collections:
  papers:
    sort_by: date
title: Mária Žuffová
exclude:
  - tailwind.config.js
  - postcss.config.js
  - webpack.config.js
  - package.json
  - package-lock.json
  - README.md
email: maria.zuffova@eui.eu
description: Personal profile website
