plugins:
  - jekyll-feed
author:
  first_name: Mária
  surname: Žuffová
  title: Researcher
  location: European University Institute
  image: /assets/img/09_maria_zuffova.jpg
social:
  linkedin: ""
  twitter: https://twitter.com/mariazuffova
  researchgate: https://www.researchgate.net/profile/Maria_Zuffova2
  scholar: https://scholar.google.com/citations?user=V7aVzF0AAAAJ&hl=sk&oi=ao
title: Mária Žuffová
email: maria.zuffova@eui.eu
url: https://mariazuffova.com
font:
  font_link: <link
    href="https://fonts.googleapis.com/css2?family=Cardo:wght@400;700&display=swap"
    rel="stylesheet">
  font_name: Cardo
collections:
  papers:
    sort_by: date
exclude:
  - tailwind.config.js
  - postcss.config.js
  - webpack.config.js
  - package.json
  - package-lock.json
  - README.md
description: "Political Science "
